### ISSUE TITLE
Pipelines get Xray: Build Enviroment Variables

### ISSUE THREAD

**Issue by StefanIricinschi** [jenkinsci/xray-connector-plugin#15]
Hello,
Right now there is an issue when Pipeline job is used with Xray environment variables.
Is no way to get the following variables XRAY_IS_REQUEST_SUCCESSFUL,XRAY_ISSUES_MODIFIED,XRAY_RAW_RESPONSE,XRAY_TEST_EXECS,XRAY_TEST
Please make these variables accessible. 
I could think of several ways:
1) Make these environment variables
2) Make them work on pipelines
3) Return them as step result
Thank you,

**Comment by Russell616** [comment]
Hi!

Thank you for your interest in the Xray connector plugin :)
Unfortunately, our injection environment variables is not compatible with Pipeline jobs, as described in our [documentation](https://confluence.xpand-it.com/display/public/XRAY/Integration+with+Jenkins#IntegrationwithJenkins-Xray:BuildEnviromentVariables).

Regarding your suggestions:
1) These variable are already set as environment variables on a node level in Freestyle projects, unfortunately, this is not possible to be done at Pipeline jobs at this moment (see reason on the next point).

2) This limitation is due to how Jenkins itself handles the variable injection (if you want, I can provide some technical details). As such, this limitation is not exclusive form our plugin, for example, you can take a look at other popular plugin repository, the [envinjector](https://github.com/jenkinsci/envinject-plugin), and go to the _Jenkins Pipeline compatibility_ section. If you really need to extract information from the server response, the best is to use a curl call to the Xray REST API to import the results and then parse the response, or to continue to use the plugin step and parse the log file of the current build.

3) Can you provide an example how these variable could be returned as a Step Result?

Thank you!
