### ISSUE TITLE
Plugin ignores Proxy noProxyHost configuration

### ISSUE THREAD

**Issue by pauxus** [jenkinsci/xray-connector-plugin#17]
When:
- a proxy is defined on Jenkins level (to acces Jenkins update site)
- with an exclusion (no_proxy) to local urls (*.myorg.com and *.myorg.net)
- and the Jira On Premise Server is in the excluded domain (jira.myorg.net)

Connection fails. 

Reason: ProxyUtil ignores no_host entries

**Comment by Russell616** [comment]
Hi pauxus,

Thank you for using the plugin and for reporting this issue.

I was able to recreate it and I have [created a bug] and (https://jira.xpand-it.com/browse/XRAYJENKINS-85) in our issue tracker backlog. 

Since we don't use GitHub Issue to manage bug reports and feature requests, I will close this Issue in here, however, if you want to be notified of any updates relating to this bug, I suggest you to create an account at our Jira platform and "Watch" the issue.

Thank you.

**Comment by pyrrhosii** [comment]
Hi,
Did you tested it ? I'm sorry, but i installed the version 2.3.0, it still does not use my noProxyHost settings.

**Comment by Russell616** [comment]
Hi @pyrrhosii,

If you are having troubles using our plugin, please contact our [support team](https://jira.xpand-it.com/servicedesk/customer/portal/2) where you can share more details about your problem.

Thank you

**Comment by thomasgl-orange** [comment]
> Did you tested it ? I'm sorry, but i installed the version 2.3.0, it still does not use my noProxyHost settings.

@pyrrhosii: see #28 for a fix I've proposed, and a workaround you could use in the meantime (try adding `https://your-jira-server/*` to your `noProxyHost` settings)
