### ISSUE TITLE
Support OAuth authorization 

### ISSUE THREAD

**Issue by joerg1985** [jenkinsci/xray-connector-plugin#36]
Hi,

i am trying to upload test run results from Jenkins to Xray. 

Authorization using basic autorization is not possible, the server is configured to use SSO.

Here are some of the (cropped) response header:
´´´´
X-Seraph-LoginReason: AUTHENTICATION_DENIED
X-Authentication-Denied-Reason: CAPTCHA_CHALLENGE; login-url=https://...
WWW-Authenticate: OAuth realm="https%3A%2F%2F...
´´´´

I think OAuth support is missing in the connector plugin, is this correct?

**Comment by Russell616** [comment]
Hi @joerg1985 

In the response header, we can see that the request failed due to the CAPCTHA. This is a problem with the user (that you tried to use to connect to Jira), to solve it, please login directly in Jira with the same user and solve the CAPTCHA **OR**  ask your Jira admin to reset the user's login attempts counter.

Regarding the authentication method, indeed you are correct. Currently we do not support OAuth, however, we do have an [issue](https://jira.xpand-it.com/browse/XRAYJENKINS-97) for it in our backlog. If you want, please **Vote** on it so we can track the community's interest in the issue, and **Watch** the issue in order to be updated regarding any updates regarding this issue.

I will close this issue, but if you need any further assistance setting up your instance or have any more question, please open a ticket in our [support system](https://xraysupport.xpand-it.com/).
